###############################################
# CONFIGURACIÓN DEL SERVIDOR
###############################################
server.port=81


###############################################
# CONFIGURACIÓN DE BASE DE DATOS MYSQL
###############################################
spring.datasource.url=jdbc:mysql://localhost:3312/taller2025
spring.datasource.username=root
spring.datasource.password=unu2025
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


###############################################
# JPA / HIBERNATE
###############################################
# update -> crea o actualiza tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola
spring.jpa.show-sql=true

# Dialecto de MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


###############################################
# LOGGING (Opcional pero útil)
###############################################
# Muestra SQL más legible
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


###############################################
# CONFIG EXTRA (si usas JSON @RequestBody)
###############################################
spring.mvc.converters.preferred-json-mapper=jackson
